version: "3.5"

services:
  server:
    # TODO db change password
    image: ghcr.io/titanomyrma/docker-image-backupers/gitea:1.23.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea-network
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: ghcr.io/titanomyrma/docker-image-backupers/postgres:17.2-bookworm
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea-network
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  gitea-network:
    name: gitea-network
    driver: bridge